version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000" 
    expose:
      - 8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

